### ISSUE TITLE
Latest release on NPM is old

### ISSUE THREAD

**Issue by enaeseth** [flatiron/prompt#175]
There have been [a number of useful changes](https://github.com/flatiron/prompt/compare/1.0.0...master) since v1.0.0 was released to NPM. I would really appreciate a v1.1. 😊

**Comment by liamdawson** [comment]
Agreed, there's a bug with `addProperties` on 1.0 that's fixed on current master (where if the object already has the properties, it returns it as the error object).

**Comment by 3stacks** [comment]
Dead project. Repo owners don't even respond to tickets anymore.

**Comment by tedivm** [comment]
Seems like time for a fork, at least to shove the bug fixes up on npm.

**Comment by bjrmatos** [comment]
it is something rough to call a project "dead" just because you don't get a response in an issue.. mantainers must be very busy with their lives and currently without of time to take some action in the package, the last commit in the project was in february and IMO it seems far from "dead", if you need an urgent fix you can always install from github `npm install flatiron/prompt#SPECIFIC COMMIT HAS HERE`, or if you need to fix something urgent you can fork the github repository and use it in your own app `npm install YOUR-USER-NAME/prompt`, there is no need for a npm fork

**Comment by tedivm** [comment]
It's been almost two years since the last update was pushed to NPM, and this issue sat for months without comment. While someone is certainly accepting pull requests it does appear that this project is mostly on autopilot.

Forking is obviously a last resort. Perhaps you should integrate with CircleCI or something to make it easier to push updates to NPM.

**Comment by adamreisnz** [comment]
I've switched to https://www.npmjs.com/package/inquirer, seems to be actively maintained and works like a charm 👍

**Comment by caub** [comment]
new released were deployed on npm
