### ISSUE TITLE
Impossible to have default & pattern set.

### ISSUE THREAD

**Issue by jamesrom** [flatiron/prompt#85]
The default value is never used if you have a pattern set. Even if you have a pattern that matches an empty string. Weird.

**Comment by gangstead** [comment]
Agreed.  Closing old issues, but if you think this should be a feature request reopen and add the feature request label.

**Comment by jamesrom** [comment]
I'm not sure why you would close this issue just because it's old. And it clearly isn't a feature request as even an example in your own [documentation does not work](https://github.com/flatiron/prompt/blob/master/README.md#valid-property-settings) due to this bug.

**Comment by gangstead** [comment]
Yeah it's not a feature request, my bad.

I just joined the project yesterday because I started using prompt two weeks ago and noticed it was not getting updated. I asked the admins if I could join and help #138 and they asked me to do some issue triage.  There is an example where pattern and defaults are working in the [example directory ](https://github.com/flatiron/prompt/blob/master/examples/history.js#L20).  I'm not sure the code you referenced in the docs is intended to work, it's an example with every possible feature added.  It isn't enough to just copy and run unlike the programs in the example directory.  Perhaps the docs need to be updated?  If you know how to fix it please submit a pull request.

There's not really any benefit to keeping a 2 year old issue around that doesn't provide much information and hasn't gotten the community interested in fixing it.  I'm trying to get the issue list down to issues that have a useful amount of information and are likely to be fixed and or have discussion about them.  Anything else distracts from that.  Ideally that list would be down to 0 and then new issues could get prompt attention.
